INCLUDE	../star3do.typ

PATH	arilou

PACKAGE	ARILOU_CODE_PACKAGE	arilou.shp
	CODE		ARILOU_CODE			arilou.cod
	GFXRES		ARILOU_ICON_MASK_PMAP_ANIM	ariicons.ani
	GFXRES		ARILOU_MICON_MASK_PMAP_ANIM	arimicon.ani
	STRTAB		ARILOU_RACE_STRINGS		aritext.txt

PACKAGE	ARILOU_PACKAGE		arilou.shp
	GFXRES		ARILOU_BIG_MASK_PMAP_ANIM	arilou.big
	GFXRES		ARILOU_MED_MASK_PMAP_ANIM	arilou.med
	GFXRES		ARILOU_SML_MASK_PMAP_ANIM	arilou.sml
	GFXRES		WARP_BIG_MASK_PMAP_ANIM		warp.big
	GFXRES		WARP_MED_MASK_PMAP_ANIM		warp.med
	GFXRES		WARP_SML_MASK_PMAP_ANIM		warp.sml

	GFXRES		ARILOU_CAPTAIN_MASK_PMAP_ANIM	aricap.ani
	SNDRES		ARILOU_SHIP_SOUNDS		arisound.snd

	MUSICRES	ARILOU_VICTORY_SONG		ariditty.mod

