INCLUDE	../star3do.typ

PATH	urquan

PACKAGE	URQUAN_CODE_PACKAGE	urquan.shp
	CODE		URQUAN_CODE			urquan.cod
	GFXRES		URQUAN_ICON_MASK_PMAP_ANIM	urqicons.ani
	GFXRES		URQUAN_MICON_MASK_PMAP_ANIM	urqmicon.ani
	STRTAB		URQUAN_RACE_STRINGS		urqtext.txt

PACKAGE	URQUAN_PACKAGE		urquan.shp
	GFXRES		URQUAN_BIG_MASK_PMAP_ANIM	urquan.big
	GFXRES		URQUAN_MED_MASK_PMAP_ANIM	urquan.med
	GFXRES		URQUAN_SML_MASK_PMAP_ANIM	urquan.sml
	GFXRES		FUSION_BIG_MASK_PMAP_ANIM	fusion.big
	GFXRES		FUSION_MED_MASK_PMAP_ANIM	fusion.med
	GFXRES		FUSION_SML_MASK_PMAP_ANIM	fusion.sml
	GFXRES		FIGHTER_BIG_MASK_PMAP_ANIM	fight.big
	GFXRES		FIGHTER_MED_MASK_PMAP_ANIM	fight.med
	GFXRES		FIGHTER_SML_MASK_PMAP_ANIM	fight.sml
	
	GFXRES		URQUAN_CAPTAIN_MASK_PMAP_ANIM	urqcap.ani
	SNDRES		URQUAN_SHIP_SOUNDS		urqsound.snd

	MUSICRES	URQUAN_VICTORY_SONG		urqditty.mod

