INCLUDE	../star3do.typ

PATH	pkunk

PACKAGE	PKUNK_CODE_PACKAGE	pkunk.shp
	CODE		PKUNK_CODE			pkunk.cod
	GFXRES		PKUNK_ICON_MASK_PMAP_ANIM	pkuicons.ani
	GFXRES		PKUNK_MICON_MASK_PMAP_ANIM	pkumicon.ani
	STRTAB		PKUNK_RACE_STRINGS		pkutext.txt

PACKAGE	PKUNK_PACKAGE		pkunk.shp
	GFXRES		PKUNK_BIG_MASK_PMAP_ANIM	pkunk.big
	GFXRES		PKUNK_MED_MASK_PMAP_ANIM	pkunk.med
	GFXRES		PKUNK_SML_MASK_PMAP_ANIM	pkunk.sml
	GFXRES		BUG_BIG_MASK_PMAP_ANIM		bugbig.ani
	GFXRES		BUG_MED_MASK_PMAP_ANIM		bugmed.ani
	GFXRES		BUG_SML_MASK_PMAP_ANIM		bugsml.ani

	GFXRES		PKUNK_CAPTAIN_MASK_PMAP_ANIM	pkucap.ani
	SNDRES		PKUNK_SHIP_SOUNDS		pkusound.snd

	MUSICRES	PKUNK_VICTORY_SONG		pkuditty.mod

