INCLUDE	../star3do.typ

PATH	blackurq

PACKAGE	KOHR_AH_CODE_PACKAGE	blackurq.shp
	CODE		KOHR_AH_CODE			blackurq.cod
	GFXRES		KOHR_AH_ICON_MASK_PMAP_ANIM	blaicons.ani
	GFXRES		KOHR_AH_MICON_MASK_PMAP_ANIM	blamicon.ani
	STRTAB		KOHR_AH_RACE_STRINGS		blatext.txt

PACKAGE	KOHR_AH_PACKAGE		blackurq.shp
	GFXRES		KOHR_AH_BIG_MASK_PMAP_ANIM	blackurq.big
	GFXRES		KOHR_AH_MED_MASK_PMAP_ANIM	blackurq.med
	GFXRES		KOHR_AH_SML_MASK_PMAP_ANIM	blackurq.sml
	GFXRES		BUZZSAW_BIG_MASK_PMAP_ANIM	buzbig.ani
	GFXRES		BUZZSAW_MED_MASK_PMAP_ANIM	buzmed.ani
	GFXRES		BUZZSAW_SML_MASK_PMAP_ANIM	buzsml.ani
	GFXRES		GAS_BIG_MASK_PMAP_ANIM		gasbig.ani
	GFXRES		GAS_MED_MASK_PMAP_ANIM		gasmed.ani
	GFXRES		GAS_SML_MASK_PMAP_ANIM		gassml.ani
	
	GFXRES		KOHR_AH_CAPTAIN_MASK_PMAP_ANIM	blacap.ani
	SNDRES		KOHR_AH_SHIP_SOUNDS		blasound.snd

	MUSICRES	KOHR_AH_VICTORY_SONG		bladitty.mod

