INCLUDE	../../star3do.typ

PATH	comm/comandr
PACKAGE	COMMANDER_PACKAGE		comandr.con
	GFXRES			COMMANDER_PMAP_ANIM		comandr.ani
	FONTRES			COMMANDER_FONT			comandr.fon
	MUSICRES		COMMANDER_MUSIC			comandr.mod
	STRTAB			COMMANDER_COLOR_MAP		comandr.ct

PACKAGE	COMMANDER_PHRASE_PACKAGE	comandr.con
	STRTAB			COMMANDER_CONVERSATION_PHRASES	comandr.txt

PATH	comm/starbas
PACKAGE	STARBASE_PHRASE_PACKAGE		comandr.con
	STRTAB			STARBASE_CONVERSATION_PHRASES	starbas.txt
