INCLUDE	../star3do.typ

PATH	sis_ship

PACKAGE	SIS_CODE_PACKAGE	sis.dat
	CODE		SIS_CODE			sis.cod

PACKAGE	SIS_BATTLE_PACKAGE	sis.dat
	GFXRES		SIS_ICON_MASK_PMAP_ANIM		sisicons.ani

	GFXRES		SIS_BIG_MASK_PMAP_ANIM		sis.big
	GFXRES		SIS_MED_MASK_PMAP_ANIM		sis.med
	GFXRES		SIS_SML_MASK_PMAP_ANIM		sis.sml
	GFXRES		BLASTER_BIG_MASK_PMAP_ANIM	blasbig.ani
	GFXRES		BLASTER_MED_MASK_PMAP_ANIM	blasmed.ani
	GFXRES		BLASTER_SML_MASK_PMAP_ANIM	blassml.ani

	GFXRES		SIS_CAPTAIN_MASK_PMAP_ANIM	siscap.ani
	SNDRES		SIS_SHIP_SOUNDS			sissound.snd
	MUSICRES	SIS_VICTORY_SONG		sisditty.mod

PACKAGE	SIS_HYPER_PACKAGE	sis.dat
	GFXRES		SIS_HYPER_MASK_PMAP_ANIM	sishyper.ani

