INCLUDE	../../star3do.typ

PATH	comm/yehat
PACKAGE	YEHAT_PACKAGE		yehat.con
	GFXRES			YEHAT_PMAP_ANIM		yehat.ani
	FONTRES			YEHAT_FONT		yehat.ani
	MUSICRES		YEHAT_MUSIC		yehat.mod

PACKAGE	YEHAT_PHRASE_PACKAGE	yehat.con
	STRTAB			YEHAT_CONVERSATION_PHRASES	yehat.txt

PATH	comm/rebel
PACKAGE	REBEL_PHRASE_PACKAGE	yehat.con
	STRTAB			REBEL_CONVERSATION_PHRASES	rebel.txt

