INCLUDE	../star3do.typ

PATH	orz

PACKAGE	ORZ_CODE_PACKAGE	orz.shp
	CODE		ORZ_CODE			orz.cod
	GFXRES		ORZ_ICON_MASK_PMAP_ANIM		orzicons.ani
	GFXRES		ORZ_MICON_MASK_PMAP_ANIM	orzmicon.ani
	STRTAB		ORZ_RACE_STRINGS		orztext.txt

PACKAGE	ORZ_PACKAGE		orz.shp
	GFXRES		ORZ_BIG_MASK_PMAP_ANIM		orz.big
	GFXRES		ORZ_MED_MASK_PMAP_ANIM		orz.med
	GFXRES		ORZ_SML_MASK_PMAP_ANIM		orz.sml
	GFXRES		HOWITZER_BIG_MASK_PMAP_ANIM	howbig.ani
	GFXRES		HOWITZER_MED_MASK_PMAP_ANIM	howmed.ani
	GFXRES		HOWITZER_SML_MASK_PMAP_ANIM	howsml.ani
	GFXRES		TURRET_BIG_MASK_PMAP_ANIM	turbig.ani
	GFXRES		TURRET_MED_MASK_PMAP_ANIM	turmed.ani
	GFXRES		TURRET_SML_MASK_PMAP_ANIM	tursml.ani

	GFXRES		ORZ_CAPTAIN_MASK_PMAP_ANIM	orzcap.ani
	SNDRES		ORZ_SHIP_SOUNDS			orzsound.snd

	MUSICRES	ORZ_VICTORY_SONG		orzditty.mod

