INCLUDE	../star3do.typ

PATH	zoqfot

PACKAGE	ZOQFOTPIK_CODE_PACKAGE	zoqfot.shp
	CODE		ZOQFOTPIK_CODE			zoqfot.cod
	GFXRES		ZOQFOTPIK_ICON_MASK_PMAP_ANIM	zoqicons.ani
	GFXRES		ZOQFOTPIK_MICON_MASK_PMAP_ANIM	zoqmicon.ani
	STRTAB		ZOQFOTPIK_RACE_STRINGS		zoqtext.txt

PACKAGE	ZOQFOTPIK_PACKAGE		zoqfot.shp
	GFXRES		ZOQFOTPIK_BIG_MASK_PMAP_ANIM	zoqfot.big
	GFXRES		ZOQFOTPIK_MED_MASK_PMAP_ANIM	zoqfot.med
	GFXRES		ZOQFOTPIK_SML_MASK_PMAP_ANIM	zoqfot.sml
	GFXRES		SPIT_BIG_MASK_PMAP_ANIM		spitbig.ani
	GFXRES		SPIT_MED_MASK_PMAP_ANIM		spitmed.ani
	GFXRES		SPIT_SML_MASK_PMAP_ANIM		spitsml.ani
	GFXRES		STINGER_BIG_MASK_PMAP_ANIM	stibig.ani
	GFXRES		STINGER_MED_MASK_PMAP_ANIM	stimed.ani
	GFXRES		STINGER_SML_MASK_PMAP_ANIM	stisml.ani

	GFXRES		ZOQFOTPIK_CAPTAIN_MASK_PMAP_ANIM	zoqcap.ani
	SNDRES		ZOQFOTPIK_SHIP_SOUNDS		zoqsound.snd

	MUSICRES	ZOQFOTPIK_VICTORY_SONG		zoqditty.mod

