INCLUDE	../star3do.typ

PATH	human

PACKAGE	HUMAN_CODE_PACKAGE	human.shp
	CODE		HUMAN_CODE			human.cod
	GFXRES		HUMAN_ICON_MASK_PMAP_ANIM	humicons.ani
	GFXRES		HUMAN_MICON_MASK_PMAP_ANIM	hummicon.ani
	STRTAB		HUMAN_RACE_STRINGS		humtext.txt

PACKAGE	HUMAN_PACKAGE		human.shp
	GFXRES		HUMAN_BIG_MASK_PMAP_ANIM	human.big
	GFXRES		HUMAN_MED_MASK_PMAP_ANIM	human.med
	GFXRES		HUMAN_SML_MASK_PMAP_ANIM	human.sml
	GFXRES		SATURN_BIG_MASK_PMAP_ANIM	saturn.big
	GFXRES		SATURN_MED_MASK_PMAP_ANIM	saturn.med
	GFXRES		SATURN_SML_MASK_PMAP_ANIM	saturn.sml
	
	GFXRES		HUMAN_CAPTAIN_MASK_PMAP_ANIM	humcap.ani
	SNDRES		HUMAN_SHIP_SOUNDS		humsound.snd

	MUSICRES	HUMAN_VICTORY_SONG		humditty.mod

