INCLUDE	../star3do.typ

PATH	mmrnmhrm

PACKAGE	MMRNMHRM_CODE_PACKAGE	mmrnmhrm.shp
	CODE		MMRNMHRM_CODE			mmrnmhrm.cod
	GFXRES		MMRNMHRM_ICON_MASK_PMAP_ANIM	mmricons.ani
	GFXRES		MMRNMHRM_MICON_MASK_PMAP_ANIM	mmrmicon.ani
	STRTAB		MMRNMHRM_RACE_STRINGS		mmrtext.txt

PACKAGE	MMRNMHRM_PACKAGE	mmrnmhrm.shp
	GFXRES		MMRNMHRM_BIG_MASK_PMAP_ANIM	mmrnmhrm.big
	GFXRES		MMRNMHRM_MED_MASK_PMAP_ANIM	mmrnmhrm.med
	GFXRES		MMRNMHRM_SML_MASK_PMAP_ANIM	mmrnmhrm.sml
	GFXRES		TORP_BIG_MASK_PMAP_ANIM		torp.big
	GFXRES		TORP_MED_MASK_PMAP_ANIM		torp.med
	GFXRES		TORP_SML_MASK_PMAP_ANIM		torp.sml
	GFXRES		YWING_BIG_MASK_PMAP_ANIM	ywing.big
	GFXRES		YWING_MED_MASK_PMAP_ANIM	ywing.med
	GFXRES		YWING_SML_MASK_PMAP_ANIM	ywing.sml

	GFXRES		MMRNMHRM_CAPTAIN_MASK_PMAP_ANIM	mmrcap.ani
	SNDRES		MMRNMHRM_SHIP_SOUNDS		mmrsound.snd

	MUSICRES	MMRNMHRM_VICTORY_SONG		mmrditty.mod

