INCLUDE	../star3do.typ

PATH	syreen

PACKAGE	SYREEN_CODE_PACKAGE	syreen.shp
	CODE		SYREEN_CODE			syreen.cod
	GFXRES		SYREEN_ICON_MASK_PMAP_ANIM	syricons.ani
	GFXRES		SYREEN_MICON_MASK_PMAP_ANIM	syrmicon.ani
	STRTAB		SYREEN_RACE_STRINGS		syrtext.txt

PACKAGE	SYREEN_PACKAGE		syreen.shp
	GFXRES		SYREEN_BIG_MASK_PMAP_ANIM	syreen.big
	GFXRES		SYREEN_MED_MASK_PMAP_ANIM	syreen.med
	GFXRES		SYREEN_SML_MASK_PMAP_ANIM	syreen.sml
	GFXRES		DAGGER_BIG_MASK_PMAP_ANIM	dagger.big
	GFXRES		DAGGER_MED_MASK_PMAP_ANIM	dagger.med
	GFXRES		DAGGER_SML_MASK_PMAP_ANIM	dagger.sml
	
	GFXRES		SYREEN_CAPTAIN_MASK_PMAP_ANIM	syrcap.ani
	SNDRES		SYREEN_SHIP_SOUNDS		syrsound.snd

	MUSICRES	SYREEN_VICTORY_SONG		syrditty.mod

