INCLUDE	../star3do.typ

PATH	slylandr

PACKAGE	SLYLANDRO_CODE_PACKAGE	slylandr.shp
	CODE		SLYLANDRO_CODE			slylandr.cod
	GFXRES		SLYLANDRO_ICON_MASK_PMAP_ANIM	slyicons.ani
	GFXRES		SLYLANDRO_MICON_MASK_PMAP_ANIM	slymicon.ani
	STRTAB		SLYLANDRO_RACE_STRINGS		slytext.txt

PACKAGE	SLYLANDRO_PACKAGE		slylandr.shp
	GFXRES		SLYLANDRO_BIG_MASK_PMAP_ANIM	slylandr.big
	GFXRES		SLYLANDRO_MED_MASK_PMAP_ANIM	slylandr.med
	GFXRES		SLYLANDRO_SML_MASK_PMAP_ANIM	slylandr.sml

	GFXRES		SLYLANDRO_CAPTAIN_MASK_PMAP_ANIM	slycap.ani
	SNDRES		SLYLANDRO_SHIP_SOUNDS		slysound.snd

	MUSICRES	SLYLANDRO_VICTORY_SONG		slyditty.mod

