INCLUDE	../../star3do.typ

PATH	comm/melnorm

PACKAGE	MELNORME_PACKAGE	melnorm.con
	GFXRES			MELNORME_PMAP_ANIM		melnorm.ani
	FONTRES			MELNORME_FONT			melnorm.fon
	MUSICRES		MELNORME_MUSIC			melnorm.mod
	STRTAB			MELNORME_CONVERSATION_PHRASES	melnorm.txt
	STRTAB			MELNORME_COLOR_MAP		melnorm.ct
