INCLUDE	../star3do.typ

PATH	shofixti

PACKAGE	SHOFIXTI_CODE_PACKAGE	shofixti.shp
	CODE		SHOFIXTI_CODE			shofixti.cod
	GFXRES		SHOFIXTI_ICON_MASK_PMAP_ANIM	shoicons.ani
	GFXRES		SHOFIXTI_MICON_MASK_PMAP_ANIM	shomicon.ani
	STRTAB		SHOFIXTI_RACE_STRINGS		shotext.txt

PACKAGE	SHOFIXTI_PACKAGE	shofixti.shp
	GFXRES		SHOFIXTI_BIG_MASK_PMAP_ANIM	shofixti.big
	GFXRES		SHOFIXTI_MED_MASK_PMAP_ANIM	shofixti.med
	GFXRES		SHOFIXTI_SML_MASK_PMAP_ANIM	shofixti.sml
	GFXRES		DESTRUCT_BIG_MASK_ANIM		destruct.big
	GFXRES		DESTRUCT_MED_MASK_ANIM		destruct.med
	GFXRES		DESTRUCT_SML_MASK_ANIM		destruct.sml
	
	GFXRES		SHOFIXTI_CAPTAIN_MASK_PMAP_ANIM	shocap.ani

PACKAGE	OLDSHOF_PACKAGE		shofixti.shp
	GFXRES		OLDSHOF_BIG_MASK_PMAP_ANIM	oldshof.big
	GFXRES		OLDSHOF_MED_MASK_PMAP_ANIM	oldshof.med
	GFXRES		OLDSHOF_SML_MASK_PMAP_ANIM	oldshof.sml
	
	GFXRES		OLDSHOF_CAPTAIN_MASK_PMAP_ANIM	oldcap.ani

PACKAGE	SHOFIXTI_SHARED_PACKAGE	shofixti.shp
	GFXRES		DART_BIG_MASK_PMAP_ANIM		missile.big
	GFXRES		DART_MED_MASK_PMAP_ANIM		missile.med
	GFXRES		DART_SML_MASK_PMAP_ANIM		missile.sml
	SNDRES		SHOFIXTI_SHIP_SOUNDS		shosound.snd
	MUSICRES	SHOFIXTI_VICTORY_SONG		shoditty.mod

