INCLUDE	../star3do.typ

PATH	umgah

PACKAGE	UMGAH_CODE_PACKAGE	umgah.shp
	CODE		UMGAH_CODE			umgah.cod
	GFXRES		UMGAH_ICON_MASK_PMAP_ANIM	umgicons.ani
	GFXRES		UMGAH_MICON_MASK_PMAP_ANIM	umgmicon.ani
	STRTAB		UMGAH_RACE_STRINGS		umgtext.txt

PACKAGE	UMGAH_PACKAGE		umgah.shp
	GFXRES		UMGAH_BIG_MASK_PMAP_ANIM	umgah.big
	GFXRES		UMGAH_MED_MASK_PMAP_ANIM	umgah.med
	GFXRES		UMGAH_SML_MASK_PMAP_ANIM	umgah.sml
	GFXRES		SPRITZ_MASK_PMAP_ANIM		spritz.ani
	GFXRES		CONE_BIG_MASK_ANIM		cone.big
	GFXRES		CONE_MED_MASK_ANIM		cone.med
	GFXRES		CONE_SML_MASK_ANIM		cone.sml
	
	GFXRES		UMGAH_CAPTAIN_MASK_PMAP_ANIM	umgcap.ani
	SNDRES		UMGAH_SHIP_SOUNDS		umgsound.snd

	MUSICRES	UMGAH_VICTORY_SONG		umgditty.mod

