INCLUDE	../star3do.typ

PATH	ilwrath

PACKAGE	ILWRATH_CODE_PACKAGE	ilwrath.shp
	CODE		ILWRATH_CODE			ilwrath.cod
	GFXRES		ILWRATH_ICON_MASK_PMAP_ANIM	ilwicons.ani
	GFXRES		ILWRATH_MICON_MASK_PMAP_ANIM	ilwmicon.ani
	STRTAB		ILWRATH_RACE_STRINGS		ilwtext.txt

PACKAGE	ILWRATH_PACKAGE		ilwrath.shp
	GFXRES		ILWRATH_BIG_MASK_PMAP_ANIM	ilwrath.big
	GFXRES		ILWRATH_MED_MASK_PMAP_ANIM	ilwrath.med
	GFXRES		ILWRATH_SML_MASK_PMAP_ANIM	ilwrath.sml
	GFXRES		FIRE_BIG_MASK_PMAP_ANIM		fire.big
	GFXRES		FIRE_MED_MASK_PMAP_ANIM		fire.med
	GFXRES		FIRE_SML_MASK_PMAP_ANIM		fire.sml
	
	GFXRES		ILWRATH_CAPTAIN_MASK_PMAP_ANIM	ilwcap.ani
	SNDRES		ILWRATH_SHIP_SOUNDS		ilwsound.snd

	MUSICRES	ILWRATH_VICTORY_SONG		ilwditty.mod

