INCLUDE	../star3do.typ

PATH	supox

PACKAGE	SUPOX_CODE_PACKAGE	supox.shp
	CODE		SUPOX_CODE			supox.cod
	GFXRES		SUPOX_ICON_MASK_PMAP_ANIM	supicons.ani
	GFXRES		SUPOX_MICON_MASK_PMAP_ANIM	supmicon.ani
	STRTAB		SUPOX_RACE_STRINGS		suptext.txt

PACKAGE	SUPOX_PACKAGE		supox.shp
	GFXRES		SUPOX_BIG_MASK_PMAP_ANIM	supox.big
	GFXRES		SUPOX_MED_MASK_PMAP_ANIM	supox.med
	GFXRES		SUPOX_SML_MASK_PMAP_ANIM	supox.sml
	GFXRES		GOB_BIG_MASK_PMAP_ANIM		gobbig.ani
	GFXRES		GOB_MED_MASK_PMAP_ANIM		gobmed.ani
	GFXRES		GOB_SML_MASK_PMAP_ANIM		gobsml.ani

	GFXRES		SUPOX_CAPTAIN_MASK_PMAP_ANIM	supcap.ani
	SNDRES		SUPOX_SHIP_SOUNDS		supsound.snd

	MUSICRES	SUPOX_VICTORY_SONG		supditty.mod

