INCLUDE	../star3do.typ

PATH	vux

PACKAGE	VUX_CODE_PACKAGE	vux.shp
	CODE		VUX_CODE			vux.cod
	GFXRES		VUX_ICON_MASK_PMAP_ANIM		vuxicons.ani
	GFXRES		VUX_MICON_MASK_PMAP_ANIM	vuxmicon.ani
	STRTAB		VUX_RACE_STRINGS		vuxtext.txt

PACKAGE	VUX_PACKAGE		vux.shp
	GFXRES		VUX_BIG_MASK_PMAP_ANIM		vux.big
	GFXRES		VUX_MED_MASK_PMAP_ANIM		vux.med
	GFXRES		VUX_SML_MASK_PMAP_ANIM		vux.sml
	GFXRES		LIMPETS_BIG_MASK_PMAP_ANIM	limpets.big
	GFXRES		LIMPETS_MED_MASK_PMAP_ANIM	limpets.med
	GFXRES		LIMPETS_SML_MASK_PMAP_ANIM	limpets.sml
	GFXRES		SLIME_MASK_PMAP_ANIM		slime.ani
	
	GFXRES		VUX_CAPTAIN_MASK_PMAP_ANIM	vuxcap.ani
	SNDRES		VUX_SHIP_SOUNDS			vuxsound.snd

	MUSICRES	VUX_VICTORY_SONG		vuxditty.mod

