INCLUDE	../star3do.typ

PATH	androsyn

PACKAGE	ANDROSYNTH_CODE_PACKAGE	androsyn.shp
	CODE		ANDROSYNTH_CODE				androsyn.cod
	GFXRES		ANDROSYNTH_ICON_MASK_PMAP_ANIM		andicons.ani
	GFXRES		ANDROSYNTH_MICON_MASK_PMAP_ANIM		andmicon.ani
	STRTAB		ANDROSYNTH_RACE_STRINGS			andtext.txt

PACKAGE	ANDROSYNTH_PACKAGE	androsyn.shp
	GFXRES		ANDROSYNTH_BIG_MASK_PMAP_ANIM		androsyn.big
	GFXRES		ANDROSYNTH_MED_MASK_PMAP_ANIM		androsyn.med
	GFXRES		ANDROSYNTH_SML_MASK_PMAP_ANIM		androsyn.sml
	GFXRES		BUBBLE_BIG_MASK_PMAP_ANIM		bubble.big
	GFXRES		BUBBLE_MED_MASK_PMAP_ANIM		bubble.med
	GFXRES		BUBBLE_SML_MASK_PMAP_ANIM		bubble.sml
	GFXRES		BLAZER_BIG_MASK_PMAP_ANIM		blazer.big
	GFXRES		BLAZER_MED_MASK_PMAP_ANIM		blazer.med
	GFXRES		BLAZER_SML_MASK_PMAP_ANIM		blazer.sml

	GFXRES		ANDROSYNTH_CAPT_MASK_PMAP_ANIM		andcap.ani
	SNDRES		ANDROSYNTH_SHIP_SOUNDS			andsound.snd

	MUSICRES	ANDROSYNTH_VICTORY_SONG			andditty.mod

