INCLUDE	../star3do.typ

PATH	lastbat

PACKAGE	SAMATRA_CODE_PACKAGE	lastbat.sc2
	CODE		SAMATRA_CODE			lastbat.cod

PACKAGE	SAMATRA_PACKAGE		lastbat.sc2
	GFXRES		SAMATRA_BIG_MASK_ANIM		lastbat.big
	GFXRES		SAMATRA_MED_MASK_PMAP_ANIM	lastbat.med
	GFXRES		SAMATRA_SML_MASK_PMAP_ANIM	lastbat.sml
	GFXRES		SENTINEL_BIG_MASK_ANIM		senbig.ani
	GFXRES		SENTINEL_MED_MASK_PMAP_ANIM	senmed.ani
	GFXRES		SENTINEL_SML_MASK_PMAP_ANIM	sensml.ani
	GFXRES		GENERATOR_BIG_MASK_ANIM		genbig.ani
	GFXRES		GENERATOR_MED_MASK_PMAP_ANIM	genmed.ani
	GFXRES		GENERATOR_SML_MASK_PMAP_ANIM	gensml.ani

	SNDRES		SAMATRA_SHIP_SOUNDS		lassound.snd

PACKAGE	SAMATRA_STATUS_PACKAGE	lastbat.sc2
	GFXRES		SAMATRA_CAPTAIN_MASK_PMAP_ANIM	lascap.ani

