INCLUDE	../star3do.typ

PATH	melnorme

PACKAGE	MELNORME_CODE_PACKAGE	melnorme.shp
	CODE		MELNORME_CODE			melnorme.cod
	GFXRES		MELNORME_ICON_MASK_PMAP_ANIM	melicons.ani
	GFXRES		MELNORME_MICON_MASK_PMAP_ANIM	melmicon.ani
	STRTAB		MELNORME_RACE_STRINGS		meltext.txt

PACKAGE	MELNORME_PACKAGE	melnorme.shp
	GFXRES		MELNORME_BIG_MASK_PMAP_ANIM	melnorme.big
	GFXRES		MELNORME_MED_MASK_PMAP_ANIM	melnorme.med
	GFXRES		MELNORME_SML_MASK_PMAP_ANIM	melnorme.sml
	GFXRES		PUMPUP_BIG_MASK_PMAP_ANIM	pumpbig.ani
	GFXRES		PUMPUP_MED_MASK_PMAP_ANIM	pumpmed.ani
	GFXRES		PUMPUP_SML_MASK_PMAP_ANIM	pumpsml.ani
	GFXRES		CONFUSE_BIG_MASK_PMAP_ANIM	confubig.ani
	GFXRES		CONFUSE_MED_MASK_PMAP_ANIM	confumed.ani
	GFXRES		CONFUSE_SML_MASK_PMAP_ANIM	confusml.ani

	GFXRES		MELNORME_CAPTAIN_MASK_PMAP_ANIM	melcap.ani
	SNDRES		MELNORME_SHIP_SOUNDS		melsound.snd

	MUSICRES	MELNORME_VICTORY_SONG		melditty.mod

