INCLUDE	../star3do.typ

PATH	druuge

PACKAGE	DRUUGE_CODE_PACKAGE	druuge.shp
	CODE		DRUUGE_CODE			druuge.cod
	GFXRES		DRUUGE_ICON_MASK_PMAP_ANIM	druicons.ani
	GFXRES		DRUUGE_MICON_MASK_PMAP_ANIM	drumicon.ani
	STRTAB		DRUUGE_RACE_STRINGS		drutext.txt

PACKAGE	DRUUGE_PACKAGE	druuge.shp
	GFXRES		DRUUGE_BIG_MASK_PMAP_ANIM	druuge.big
	GFXRES		DRUUGE_MED_MASK_PMAP_ANIM	druuge.med
	GFXRES		DRUUGE_SML_MASK_PMAP_ANIM	druuge.sml
	GFXRES		CANNON_BIG_MASK_PMAP_ANIM	canbig.ani
	GFXRES		CANNON_MED_MASK_PMAP_ANIM	canmed.ani
	GFXRES		CANNON_SML_MASK_PMAP_ANIM	cansml.ani

	GFXRES		DRUUGE_CAPT_MASK_PMAP_ANIM	drucap.ani
	SNDRES		DRUUGE_SHIP_SOUNDS		drusound.snd

	MUSICRES	DRUUGE_VICTORY_SONG		druditty.mod

