INCLUDE	../star3do.typ

PATH	mycon

PACKAGE	MYCON_CODE_PACKAGE	mycon.shp
	CODE		MYCON_CODE			mycon.cod
	GFXRES		MYCON_ICON_MASK_PMAP_ANIM	mycicons.ani
	GFXRES		MYCON_MICON_MASK_PMAP_ANIM	mycmicon.ani
	STRTAB		MYCON_RACE_STRINGS		myctext.txt

PACKAGE	MYCON_PACKAGE		mycon.shp
	GFXRES		MYCON_BIG_MASK_PMAP_ANIM	mycon.big
	GFXRES		MYCON_MED_MASK_PMAP_ANIM	mycon.med
	GFXRES		MYCON_SML_MASK_PMAP_ANIM	mycon.sml
	GFXRES		PLASMA_BIG_MASK_PMAP_ANIM	plasma.big
	GFXRES		PLASMA_MED_MASK_PMAP_ANIM	plasma.med
	GFXRES		PLASMA_SML_MASK_PMAP_ANIM	plasma.sml
	
	GFXRES		MYCON_CAPTAIN_MASK_PMAP_ANIM	myccap.ani
	SNDRES		MYCON_SHIP_SOUNDS		mycsound.snd

	MUSICRES	MYCON_VICTORY_SONG		mycditty.mod

