INCLUDE	../star3do.typ

PATH	chenjesu

PACKAGE	CHENJESU_CODE_PACKAGE	chenjesu.shp
	CODE		CHENJESU_CODE			chenjesu.cod
	GFXRES		CHENJESU_ICON_MASK_PMAP_ANIM	cheicons.ani
	GFXRES		CHENJESU_MICON_MASK_PMAP_ANIM	chemicon.ani
	STRTAB		CHENJESU_RACE_STRINGS		chetext.txt

PACKAGE	CHENJESU_PACKAGE	chenjesu.shp
	GFXRES		CHENJESU_BIG_MASK_PMAP_ANIM	chenjesu.big
	GFXRES		CHENJESU_MED_MASK_PMAP_ANIM	chenjesu.med
	GFXRES		CHENJESU_SML_MASK_PMAP_ANIM	chenjesu.sml
	GFXRES		SPARK_BIG_MASK_PMAP_ANIM	spark.big
	GFXRES		SPARK_MED_MASK_PMAP_ANIM	spark.med
	GFXRES		SPARK_SML_MASK_PMAP_ANIM	spark.sml
	GFXRES		DOGGY_BIG_MASK_PMAP_ANIM	doggy.big
	GFXRES		DOGGY_MED_MASK_PMAP_ANIM	doggy.med
	GFXRES		DOGGY_SML_MASK_PMAP_ANIM	doggy.sml
	
	GFXRES		CHENJESU_CAPTAIN_MASK_PMAP_ANIM	checap.ani
	SNDRES		CHENJESU_SHIP_SOUNDS		chesound.snd

	MUSICRES	CHENJESU_VICTORY_SONG		cheditty.mod

