INCLUDE	../star3do.typ

PATH	chmmr

PACKAGE	CHMMR_CODE_PACKAGE	chmmr.shp
	CODE		CHMMR_CODE			chmmr.cod
	GFXRES		CHMMR_ICON_MASK_PMAP_ANIM	chmicons.ani
	GFXRES		CHMMR_MICON_MASK_PMAP_ANIM	chmmicon.ani
	STRTAB		CHMMR_RACE_STRINGS		chmtext.txt

PACKAGE	CHMMR_PACKAGE		chmmr.shp
	GFXRES		CHMMR_BIG_MASK_PMAP_ANIM	chmmr.big
	GFXRES		CHMMR_MED_MASK_PMAP_ANIM	chmmr.med
	GFXRES		CHMMR_SML_MASK_PMAP_ANIM	chmmr.sml
	GFXRES		MUZZLE_BIG_MASK_PMAP_ANIM	muzbig.ani
	GFXRES		MUZZLE_MED_MASK_PMAP_ANIM	muzmed.ani
	GFXRES		MUZZLE_SML_MASK_PMAP_ANIM	muzsml.ani
	GFXRES		SATELLITE_BIG_MASK_PMAP_ANIM	satbig.ani
	GFXRES		SATELLITE_MED_MASK_PMAP_ANIM	satmed.ani
	GFXRES		SATELLITE_SML_MASK_PMAP_ANIM	satsml.ani

	GFXRES		CHMMR_CAPTAIN_MASK_PMAP_ANIM	chmcap.ani
	SNDRES		CHMMR_SHIP_SOUNDS		chmsound.snd

	MUSICRES	CHMMR_VICTORY_SONG		chmditty.mod

