INCLUDE	../star3do.typ

PATH	spathi

PACKAGE	SPATHI_CODE_PACKAGE	spathi.shp
	CODE		SPATHI_CODE			spathi.cod
	GFXRES		SPATHI_ICON_MASK_PMAP_ANIM	spaicons.ani
	GFXRES		SPATHI_MICON_MASK_PMAP_ANIM	spamicon.ani
	STRTAB		SPATHI_RACE_STRINGS		spatext.txt

PACKAGE	SPATHI_PACKAGE		spathi.shp
	GFXRES		SPATHI_BIG_MASK_PMAP_ANIM	spathi.big
	GFXRES		SPATHI_MED_MASK_PMAP_ANIM	spathi.med
	GFXRES		SPATHI_SML_MASK_PMAP_ANIM	spathi.sml
	GFXRES		MISSILE_BIG_MASK_PMAP_ANIM	missile.big
	GFXRES		MISSILE_MED_MASK_PMAP_ANIM	missile.med
	GFXRES		MISSILE_SML_MASK_PMAP_ANIM	missile.sml
	GFXRES		DISCRIM_BIG_MASK_PMAP_ANIM	discrim.big
	GFXRES		DISCRIM_MED_MASK_PMAP_ANIM	discrim.med
	GFXRES		DISCRIM_SML_MASK_PMAP_ANIM	discrim.sml
	
	GFXRES		SPATHI_CAPTAIN_MASK_PMAP_ANIM	spacap.ani
	SNDRES		SPATHI_SHIP_SOUNDS		spasound.snd

	MUSICRES	SPATHI_VICTORY_SONG		spaditty.mod

