INCLUDE	../star3do.typ

PATH	utwig

PACKAGE	UTWIG_CODE_PACKAGE	utwig.shp
	CODE		UTWIG_CODE			utwig.cod
	GFXRES		UTWIG_ICON_MASK_PMAP_ANIM	utwicons.ani
	GFXRES		UTWIG_MICON_MASK_PMAP_ANIM	utwmicon.ani
	STRTAB		UTWIG_RACE_STRINGS		utwtext.txt

PACKAGE	UTWIG_PACKAGE		utwig.shp
	GFXRES		UTWIG_BIG_MASK_PMAP_ANIM	utwig.big
	GFXRES		UTWIG_MED_MASK_PMAP_ANIM	utwig.med
	GFXRES		UTWIG_SML_MASK_PMAP_ANIM	utwig.sml
	GFXRES		LANCE_BIG_MASK_PMAP_ANIM	lanbig.ani
	GFXRES		LANCE_MED_MASK_PMAP_ANIM	lanmed.ani
	GFXRES		LANCE_SML_MASK_PMAP_ANIM	lansml.ani

	GFXRES		UTWIG_CAPTAIN_MASK_PMAP_ANIM	utwcap.ani
	SNDRES		UTWIG_SHIP_SOUNDS		utwsound.snd

	MUSICRES	UTWIG_VICTORY_SONG		utwditty.mod

