INCLUDE	../star3do.typ

PATH	yehat

PACKAGE	YEHAT_CODE_PACKAGE	yehat.shp
	CODE		YEHAT_CODE			yehat.cod
	GFXRES		YEHAT_ICON_MASK_PMAP_ANIM	yehicons.ani
	GFXRES		YEHAT_MICON_MASK_PMAP_ANIM	yehmicon.ani
	STRTAB		YEHAT_RACE_STRINGS		yehtext.txt

PACKAGE	YEHAT_PACKAGE		yehat.shp
	GFXRES		YEHAT_BIG_MASK_PMAP_ANIM	yehat.big
	GFXRES		YEHAT_MED_MASK_PMAP_ANIM	yehat.med
	GFXRES		YEHAT_SML_MASK_PMAP_ANIM	yehat.sml
	GFXRES		CANNON_BIG_MASK_PMAP_ANIM	missile.big
	GFXRES		CANNON_MED_MASK_PMAP_ANIM	missile.med
	GFXRES		CANNON_SML_MASK_PMAP_ANIM	missile.sml
	GFXRES		SHIELD_BIG_MASK_ANIM		shield.big
	GFXRES		SHIELD_MED_MASK_ANIM		shield.med
	GFXRES		SHIELD_SML_MASK_ANIM		shield.sml
	
	GFXRES		YEHAT_CAPTAIN_MASK_PMAP_ANIM	yehcap.ani
	SNDRES		YEHAT_SHIP_SOUNDS		yehsound.snd

	MUSICRES	YEHAT_VICTORY_SONG		yehditty.mod

