INCLUDE	../star3do.typ

PATH	thradd

PACKAGE	THRADDASH_CODE_PACKAGE	thradd.shp
	CODE		THRADDASH_CODE			thradd.cod
	GFXRES		THRADDASH_ICON_MASK_PMAP_ANIM	thricons.ani
	GFXRES		THRADDASH_MICON_MASK_PMAP_ANIM	thrmicon.ani
	STRTAB		THRADDASH_RACE_STRINGS		thrtext.txt

PACKAGE	THRADDASH_PACKAGE		thradd.shp
	GFXRES		THRADDASH_BIG_MASK_PMAP_ANIM	thradd.big
	GFXRES		THRADDASH_MED_MASK_PMAP_ANIM	thradd.med
	GFXRES		THRADDASH_SML_MASK_PMAP_ANIM	thradd.sml
	GFXRES		HORN_BIG_MASK_PMAP_ANIM		horbig.ani
	GFXRES		HORN_MED_MASK_PMAP_ANIM		hormed.ani
	GFXRES		HORN_SML_MASK_PMAP_ANIM		horsml.ani
	GFXRES		NAPALM_BIG_MASK_PMAP_ANIM	napbig.ani
	GFXRES		NAPALM_MED_MASK_PMAP_ANIM	napmed.ani
	GFXRES		NAPALM_SML_MASK_PMAP_ANIM	napsml.ani

	GFXRES		THRADDASH_CAPTAIN_MASK_PMAP_ANIM	thrcap.ani
	SNDRES		THRADDASH_SHIP_SOUNDS		thrsound.snd

	MUSICRES	THRADDASH_VICTORY_SONG		thrditty.mod

